# Generated by Django 3.1.2 on 2020-11-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('fechaLanzamiento', models.DateField()),
                ('idioma', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('descripcion', models.TextField(max_length=400)),
                ('peso', models.IntegerField()),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.autor')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.categoria')),
                ('idEdiitorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.DateField()),
                ('fechaentrada', models.DateField()),
                ('idLector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.lector')),
                ('idLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.libro')),
            ],
        ),
    ]
