# Generated by Django 3.1.2 on 2020-11-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='idEdiitorial',
            new_name='idEditorial',
        ),
    ]
