# Generated by Django 4.0.5 on 2022-06-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_libro_idautor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='idLector',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='idLibro',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='idEditorial',
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
    ]
