# Generated by Django 3.1.2 on 2020-11-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201124_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='idAutor',
        ),
    ]
